### ISSUE TITLE
Enable support for moonraker update manager by adding a tag

### ISSUE THREAD

**Issue by drandarov-io** [Desuuuu/klipper#58]
Forks of Klipper can apparently only be properly parsed by the update manager in moonraker if a git tag is present according to a conversation with the developer.
I'm not sure if thats feasible with you setup for auto-updates, but maybe you can look into it.

**Comment by drandarov-io** [comment]
![image](https://user-images.githubusercontent.com/13102251/122606538-5f189980-d079-11eb-9bc6-879cfbf1b852.png)

**Comment by Desuuuu** [comment]
I don't really tag anything on the main branch since there isn't really any "release" upstream. If that makes a difference for you, then I'll start tagging when I merge upstream changes.

Indeed, there are also the tags from the upstream sync action, but I tend to clear these after I manually merge.

**Comment by drandarov-io** [comment]
It would improve compatibility with Mainsail and Moonraker, so I would be very thankful :)

**Comment by Desuuuu** [comment]
Should be good now. I'll try to keep that in mind.
